### ISSUE TITLE
Needs a refresh after every level to work properly.

### ISSUE THREAD

**Issue by RaphaelSantiago53** [dlvhdr/hebrew-touch-typing#2]
I love this website but just a small bug on Firefox.

It works fine when I've just opened it but when I finish the first level, it just stops reading key presses any more. Then, after I refresh the page, it works fine but that again only lasts for one level and then I have to refresh again. And so on for every level.

**Comment by sam-mfb** [comment]
I submitted a PR to fix this issue.
