### ISSUE TITLE
apostrophe character "'" doesn't work on mac keyboard

### ISSUE THREAD

**Issue by akivaschiff** [dlvhdr/hebrew-touch-typing#3]
The apostrophe character (W in english) on the mac keyboard is not recognized by the app as an apostrophe (example, see lesson 14). It marks that we have a mistake instead of accepting it.

**Comment by sam-mfb** [comment]
i submitted a PR to fix this.

**Comment by skyeterran** [comment]
Just writing to say that although this issue is fixed on local builds, the geresh on Mac still isn't recognized on [the online version of this app](https://typing.dlvhdr.me) - I assume that it's just not up-to-date with the merged PR from last year, at least that's what it looks like!

**Comment by dlvhdr** [comment]
I will update the remote version later this week

**Comment by dlvhdr** [comment]
Done
